version: '2'
services:
  freenet:
    container_name: freenet
    image: infincia/docker-freenet:master
    ports:
      - "8888:8888"
      - "9481:9481"
    volumes:
      - /conf/freenet:/conf
      - /data/freenet:/data
